# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itemDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_itemDialog(object):
    def setupUi(self, itemDialog):
        itemDialog.setObjectName("itemDialog")
        itemDialog.resize(300, 170)
        self.verticalLayout = QtWidgets.QVBoxLayout(itemDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLineEdit(itemDialog)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(itemDialog)
        self.label.setMaximumSize(QtCore.QSize(30, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cost = QtWidgets.QDoubleSpinBox(itemDialog)
        self.cost.setMaximum(16777215.0)
        self.cost.setSingleStep(0.01)
        self.cost.setObjectName("cost")
        self.horizontalLayout_2.addWidget(self.cost)
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioCount = QtWidgets.QRadioButton(itemDialog)
        self.radioCount.setObjectName("radioCount")
        self.verticalLayout_2.addWidget(self.radioCount)
        self.radioMass = QtWidgets.QRadioButton(itemDialog)
        self.radioMass.setObjectName("radioMass")
        self.verticalLayout_2.addWidget(self.radioMass)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.status = QtWidgets.QLabel(itemDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.status.setPalette(palette)
        self.status.setText("")
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(itemDialog)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(itemDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(itemDialog)
        QtCore.QMetaObject.connectSlotsByName(itemDialog)

    def retranslateUi(self, itemDialog):
        _translate = QtCore.QCoreApplication.translate
        itemDialog.setWindowTitle(_translate("itemDialog", "Товар"))
        self.name.setPlaceholderText(_translate("itemDialog", "Наименование"))
        self.label.setText(_translate("itemDialog", "Цена:"))
        self.radioCount.setText(_translate("itemDialog", "Штучный"))
        self.radioMass.setText(_translate("itemDialog", "Весовой"))
        self.btnSave.setText(_translate("itemDialog", "Сохранить"))
        self.btnCancel.setText(_translate("itemDialog", "Отмена"))
